### ISSUE TITLE
Fix NTA SQL errors

### ISSUE THREAD

**Issue by lindsaypoirier** [BetaNYC/nyc-boundaries#12]
When users select Neighborhood Tabulation Area from the Query Overlapping districts dropdown, and then select 'Airport' or 'Hammels-Averne-Edgemere' (and I'm assuming some others), some of the boundaries (e.g. Police Precincts, Congressional districts, etc.) do not query.

For those boundaries, the console reports:
Failed to load resource: the server responded with a status of 400 (Bad Request)

**Comment by zhik** [comment]
#22 
A query of 'Airport' or 'Hammels-Averne-Edgemere' will now work.

But the Airport query will return intersecting boundaries for both JFK and LGA. This can be fixed by modifying the data beforehand or in Carto. 
![image](https://user-images.githubusercontent.com/9166469/68339341-695b6f00-00b2-11ea-8283-4e7316fe6e56.png)
